### ISSUE TITLE
genome of seqinfo in serialized RDS

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/MultiAssayExperiment#128]
for ovarian, in the genome of the seqinfo of the mutations Elist element I am seeing "36".  we should use a more conventional token?  although perhaps it is autoderived from the build field of the metadata.  i think we should use something compatible with the seqlevels in use, implying hg18 for "36".

**Comment by lwaldron** [comment]
Should fill in genome for every range-based dataset, even if it can't be extracted automatically from that dataset and requires curation.

**Comment by vjcitn** [comment]
can it be automated given "standard" TCGA content?  do we check
compatibility of all GRanges in an MAE for common 'genome' field?

**Comment by vjcitn** [comment]
also -- maybe start a new issue: we should have a liftOver utility taking
one MAE to another.

**Comment by lwaldron** [comment]
> can it be automated given "standard" TCGA content? 

@LiNk-NY is the genome build available in all the range-based TCGA input data you are using?

> do we check compatibility of all GRanges in an MAE for common 'genome' field?

Currently no, but this is a good idea. All range-based Elist elements should have the same value in the 'genome' slot.  All missing could be allowed, since most people creating their own MAE would likely be using the same genome whatever that is.

> also -- maybe start a new issue: we should have a liftOver utility taking one MAE to another. 

Would that in general be possible given the one-to-many mapping of rtracklayer::liftOver()?  What should happen to a RangedSummarizedExperiment when there are one-to-many mappings of ranges - duplicated rows?  For RangedRaggedAssay it wouldn't be a problem, since rtracklayer::liftOver() could just be applied to each list element.  It seems to me that rtracklayer::liftOver() would have to be extended to act on the ranged-based assays that we support in MultiAssayExperiment, so that it could be applied directly to its elements.

**Comment by LiNk-NY** [comment]
The "standard" TCGA content does not always include the genome build. For some datasets, you may have a column indicating "NCBI_build" variable but other datasets don't have such convenience. 
It may be possible to extract the particular genome build from the long filenames obtained from the Firehose pipeline (RTCGAToolbox). 
It's not apparent to me that the genome builds are consistent across ranged datasets. I will look into this further.

**Comment by vjcitn** [comment]
I would throw a warning or an error when NA is found in the genome slot of
anything holding addresses in a GRanges.  While I understand that addresses
in different objects may be compatible even if their reference is unknown
it is still dangerous for combining with other data of potentially
different reference.

**Comment by LiNk-NY** [comment]
Btw, is it safe to assume that NCBI_build `37` refers to Genome Reference Consortium `GRCh37` and thus `hg19`?

**Comment by lwaldron** [comment]
According to the UCSC genome browser [FAQ](https://genome.ucsc.edu/FAQ/FAQreleases.html), "NCBI build 37" would be a misnomer, but that probably refers to Genome Reference Consortium GRCh37 and hg19.

**Comment by LiNk-NY** [comment]
This should belong in https://github.com/Bioconductor/MultiOmicQC/issues
