### ISSUE TITLE
inappropriate package installation in vignettes

### ISSUE THREAD

**Issue by mtmorgan** [waldronlab/MultiAssayExperiment#224]
It's inappropriate to install packages 'on the fly' into system libraries (packages used only in vignettes should be in the Vignettes: field). It is not allowed to use non-CRAN or Bioconductor packages in Bioconductor packages. Even / especially for intimates of the project.

https://github.com/waldronlab/MultiAssayExperiment/blame/master/vignettes/pradMAEO-RTCGAToolbox.Rmd#L32

@kalibera

**Comment by LiNk-NY** [comment]
Hi Martin @mtmorgan,
We are fully aware of the issue and will soon be resolved once `TCGAutils` is in Bioconductor. 
Best regards,
Marcel

**Comment by mtmorgan** [comment]
A package is either in or not in Bioconductor. TCGAutils is not in Bioconductor.

**Comment by LiNk-NY** [comment]
I will use `eval = FALSE` in the meantime. Thanks.

**Comment by lwaldron** [comment]
With curatedTCGAData now availale you can get the same data much more simply, and this vignette was about getting the data rather than teaching something. So I'm inclined to think this vignette has reached the end of its usefulness, and would belong in the RTCGAToolbox package if anywhere. Glad to hear a counter-point though.
