### ISSUE TITLE
Experiment Can Be A Data Frame

### ISSUE THREAD

**Issue by DarioS** [waldronlab/MultiAssayExperiment#232]
I noticed that a `data.frame` is allowed to the constructor of `MultiAssayExperiment`. However, subsetting causes it to be dropped. Should it be prohibited unless it's clinical data input as `colData`?

```
RNAmatrix <- matrix(rnorm(25), ncol = 5)
colnames(RNAmatrix) <- paste("Sample", 1:5)
rownames(RNAmatrix) <- paste("Gene", 1:5)
dataTable <- data.frame(Score = 1:5, row.names = paste("Sample", 1:5))
container <- MultiAssayExperiment(list(RNA = RNAmatrix, test = dataTable))
container[, c("Sample 2", "Sample 3"), ]
```

The `test` table is removed from the container. There's probably no use case of an assay that generates mixed data types (i.e. discrete and numeric), so the input could be restricted to variables based on a matrix structure.

**Comment by vjcitn** [comment]
I am not sure I understand this.  The data.frame you supplied has samples
in rows.  If you
use upsetSamples(container) you will see that there are no samples in
common among
the experiment elements.  There may be an ambiguity in the doc that needs
to address this.

**Comment by LiNk-NY** [comment]
Hi Dario, @DarioS 

The `data.frame` input is valid under the checks and the API.
This could very well be an experiment on a single sample. But without providing a 
`sampleMap` there's no way of knowing that the "orientation" of the `data.frame` is off.

We could add a warning for any `data.frame` / `DataFrame` input due to the potential of
mixed data types, as you stated.

Regards,
Marcel
