### ISSUE TITLE
nested experiments

### ISSUE THREAD

**Issue by phaverty** [waldronlab/MultiAssayExperiment#258]
Good morning. I've been working a lot with MAE recently. Thanks for making it! It looks like MAE doesn't like experiments to have more than one assay.  I work a lot with Experiments that are SummarizedExperiments with multiple assay matrices.  MAE features like `assays` and `wideFormat` seem to ignore all but the first matrix. Is this by design? (Am I doing it wrong?)

**Comment by LiNk-NY** [comment]
Hi Peter, @phaverty 

I'm glad to hear you're making use of our software!

Yes, this is by design. Although there is an `i` argument in `wideFormat`, it gets passed to all `assays` so you would only use it if all `SummarizedExperiment`s in the `MultiAssayExperiment` have the (at least) _same_ number of assays as `i` BUT it will only extract that particular assay. 
I would recommend to separate these out into separate assays in the `ExperimentList`.
You could also use the `c` method for `MultiAssayExperiment` to append those additional experiments based on an existing experiment.

Best regards,
Marcel
