### ISSUE TITLE
Why does colnames(mae) return a character list?

### ISSUE THREAD

**Issue by LTLA** [waldronlab/MultiAssayExperiment#288]
This is not expected:

```r
library(MultiAssayExperiment)

# Making up some data.
mat <- matrix(rpois(10000, 5), nrow=10)
rownames(mat) <- paste0("CD", seq_len(nrow(mat))) # made-up markers
colnames(mat) <- paste0("BARCODE_", seq_len(ncol(mat))) # made-up barcodes

# First building the SE. Assuming that barcodes come from a range of donors.
donor <- rep(LETTERS[1:10], each=100)
se <- SummarizedExperiment(list(counts=mat))
se$Donor <- donor

# Now building the MAE. Each 'column' of the MAE corresponds to a donor;
# this is specified by the sample mapping from donors (primary) to barcodes (colname).
mae <- MultiAssayExperiment(list(markers=se),
    sampleMap=data.frame(assay="markers", primary=se$Donor, colname=colnames(se)),
    colData=DataFrame(row.names=LETTERS[1:10])
)
colnames(mae)
## CharacterList of length 1
## [["markers"]] BARCODE_1 BARCODE_2 BARCODE_3 ... BARCODE_999 BARCODE_1000
```

What I really want requires an unintuitive extra step:

```r
rownames(colData(mae))
## [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J"
```

I don't understand why these two calls are different. If the `colData` of an object has row names, those should be the `colnames` of the object by definition. If I wanted the column names of the individual SEs, I'd look them up individually.

**Comment by lwaldron** [comment]
This went through quite a bit of discussion back in the day, because there are opposing perspectives on what rownames and colnames should return and it's still not clear to me that there's a right answer. As a guide we turned to SummarizedExperiment as much as possible, and SummarizedExperiment does require `rownames(colData(mae))` to return the rownames of the colData (below). It was from these behaviors of SummarizedExperiment that we decided that the CharacterLists returned were most conceptually similar to behavior expected from SummarizedExperiment. That said, there is also the usual contract that rownames and colnames return atomic vectors or NULL, and from that perspective perhaps they should just return an error or NULL for MultiAssayExperiment, but that seems like taking away functionality to make nobody happy. 

Like you point out, for a SE, `rownames(colData(se))` is identical to `colnames(se)`, but that is a naming convenience possible because of the 1:1 relationship between colData and assay data for SummarizedExperiment.  It breaks down for MultiAssayExperiment because each assay can have different samples that do not need match 1:1 to `rownames(colData(se))`. So that unintuitive difference does arise from a fundamental difference in the kinds of experiments these objects can represent. I'm still unconvinced that either of these solutions is "correct", and the most "correct" solution still may be to take away rownames and colnames with an error message pointing to two related functions with these two different behaviors.  I'll move this issue onto Discussions for now...

```r
suppressPackageStartupMessages(library(SummarizedExperiment))
mat <- matrix(rpois(10000, 5), nrow=10)
rownames(mat) <- paste0("CD", seq_len(nrow(mat))) # made-up markers
colnames(mat) <- paste0("BARCODE_", seq_len(ncol(mat))) # made-up barcodes

# First building the SE. Assuming that barcodes come from a range of donors.
donor <- rep(LETTERS[1:10], each=100)
se <- SummarizedExperiment(list(counts=mat))
se$Donor <- donor
```

```r
rownames(se)
#>  [1] "CD1"  "CD2"  "CD3"  "CD4"  "CD5"  "CD6"  "CD7"  "CD8"  "CD9"  "CD10"
rownames(colData(se))
#>    [1] "BARCODE_1"    "BARCODE_2"    "BARCODE_3"    "BARCODE_4"   
#>    [5] "BARCODE_5"    "BARCODE_6"    "BARCODE_7"    "BARCODE_8"   
## (cut)
```
